### ISSUE TITLE
it makes mini wave trail look bad

### ISSUE THREAD

**Issue by martan2010** [nytelytee/geode-wave-trail-drag-fix#11]
![image](https://github.com/user-attachments/assets/7c7bb9b8-3046-49a3-b40a-cc44d16485d9)

it just does, i dont feel like using it like this lol

**Comment by nytelytee** [comment]
Do you use Click Between Frames?

**Comment by martan2010** [comment]
yes, that may be the issue, but it doesnt happen on mobile (and i use cbf there also)

**Comment by nytelytee** [comment]
CBF does not exist on mobile. You are probably referring to Click on Steps, which wouldn't break the trail in this way either way.

Anyway, this used to happen prior to 2.206 as well, but I had a fix for it, which appears to have stopped working in 2.206 for some reason.

**Comment by martan2010** [comment]
ok, well i will stop using the mod until i beat bloodbath, ill turn it on later tho :)
or if the fix will be working again

**Comment by nytelytee** [comment]
Update: this appears to actually be a CBF bug(?). Not sure if the behavior is intended, but the time between updates is reported as 0 instead of splitting up 0.25 (by default the time between 2 updates is reported as 0.25, so ideally CBF 'splitting' the update should report as 2 updates that sum up to 0.25 (e.g. 0.23 and 0.02)), which used to be the case, but now is not for some reason. CBF still seems to **work** however, but it does ruin my fix.

**Comment by nytelytee** [comment]
It should be fixed now.
