### ISSUE TITLE
Bug with mini wave

### ISSUE THREAD

**Issue by NeuronExtractor** [nytelytee/geode-wave-trail-drag-fix#3]
![20240304172627_1](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/118637745/c419d96b-aa8a-482e-b0ee-cada5f27cc72)
![20240304172940_1](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/118637745/d64ed87c-138e-43ff-a57c-b39c8531c3a5)
There is a bug when on mini wave where (only) if you are going up (down when gravity's flipped) the trail breaks as usual. I noticed this when playing Nhelv by SrGuillester and realized it happens with or without slopes as shown in the images.

**Comment by NeuronExtractor** [comment]
![20240304174642_1](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/118637745/298ab2f8-0de0-4d41-930c-4508abf7011c)
![20240304174615_1](https://github.com/nytelytee/geode-wave-trail-drag-fix/assets/118637745/a10acfea-583c-40e7-820b-e60e13dda90e)
I've just noticed it also happens when going down but only if there's blocks before the slope you fall off of (both of these images are in normal gravity

**Comment by nytelytee** [comment]
Using the method from v1.0.2, which I can see is the version you're using from the fact that the slant bug is present (it was fixed in v1.0.3, which wasn't on the index), it is impossible to tell when that slope changes because the method is based on the game's reporting of velocity, although in this case I think it was due to an error in the way I tried to make slopes smoother. Regardless, I've published v1.1.0, which uses a completely different method to detect angle changes, and in this case, it addresses that, although it looks a little worse on slopes in certain cases. I have submitted v1.1.0 to the index, but it wasn't accepted yet. You can download it directly from releases.

**Comment by NeuronExtractor** [comment]
works perfectly now
